---
apiVersion: rds.aws.upbound.io/v1beta1
kind: ClusterParameterGroup
metadata:
  name: mysql-cluster-parameter-group-v1beta1-<< .config.rds.primary.region >>
  label:
    provider: aws
    region: << .config.rds.primary.region >>
    version: v1beta1
spec:
  forProvider:
    region: << .config.rds.primary.region >>
    description: RDS default mysql cluster parameter group
    family: << .config.rds.mysql.family >>
    parameter:
      - name: character_set_server
        value: utf8
      - name: character_set_client
        value: utf8
      - name: time_zone
        value: UTC
      - name: character_set_connection
        value: utf8
      - name: character_set_database
        value: utf8
      - name: character_set_results
        value: utf8
      - name: binlog_format
        value: ROW
        applyMethod: pending-reboot
      - name: server_audit_logging
        value: '1'
      - name: server_audit_logs_upload
        value: '1'
      - name: server_audit_events
        value: CONNECT,QUERY_DCL,QUERY_DDL

---
apiVersion: rds.aws.upbound.io/v1beta1
kind: ParameterGroup
metadata:
  labels:
    service_name: global-example
  name: global-example
  namespace: pe
spec:
  forProvider:
    region: us-east-1
    description: global-example
    family: aurora-mysql8.0
    parameter:
      - name: "max_connections"
        value: "1000"
    tags:
      Name: global-example
      deployment_method: Crossplane
      service_name: global-example
      team: "Platform Kompute"