---
apiVersion: aws.v1beta1.afterpay.cloud/v1beta1
kind: RMysql
metadata:
  name: regional-mysql-deleteme-vtest
  namespace: pe
  labels:
    version: v1beta1
    serviceId: regional-mysql-deleteme-vtest
spec:
  datbaseName: mysql
  engineVersion: 8.0.mysql_aurora.3.03.1
  parameterGroupFamily: aurora-mysql8.0
  deletionProtection: false
  skipFinalSnapshot: true
  performanceInsightsEnabled: true
  backupRetentionPeriod: 7
  preferredBackupWindow: 12:00-13:00
  preferredMaintenanceWindow: wed:10:00-wed:11:00
  applyImmediately: true
  repicas:
    - name: usea1
      type: primary
      dbInstanceCount: 1
      dbClusterInstanceClass: db.r5.large
  compositionSelector:
    matchLabels:
      version: v1beta1
      provider: aws
      cluster: regional
