---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: rpostgres.aws.v1beta1.afterpay.cloud
  labels:
    version: v1beta1
spec:
  group: aws.v1beta1.afterpay.cloud
  names:
    kind: XRPostgres
    plural: xrpostgres
  claimNames:
    kind: RPostgres
    plural: rpostgres
  versions:
  - name: v1beta1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              datbaseName:
                type: string
              engineVersion:
                type: string
              parameterGroupFamily:
                type: string  
              skipFinalSnapshot:
                type: boolean
              deletionProtection:
                type: boolean
              dbClusterInstanceClass:
                type: string
              required:
                - datbaseName
                - engineVersion
                - parameterGroupFamily
                - skipFinalSnapshot
                - deletionProtection
                - dbClusterInstanceClass
              x-kubernetes-preserve-unknown-fields: true
          status:
            description: Status defines the observed state
            type: object
            properties:
              outputs:
                description: Freeform field containing status information for regional postgres
                type: object
                x-kubernetes-preserve-unknown-fields: true