---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xrpostgres.aws.v1beta1.afterpay.cloud
  labels:
    version: v1beta1
spec:
  group: aws.v1beta1.afterpay.cloud
  names:
    kind: XRPostgres
    plural: xrpostgres
  claimNames:
    kind: RPostgres
    plural: rpostgres
  versions:
    - name: v1beta1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                datbaseName:
                  type: string
                engineVersion:
                  type: string
                parameterGroupFamily:
                  type: string  
                deletionProtection:
                  type: boolean
                dbClusterInstanceClass:
                  type: string
                dbInstanceCount:
                  type: number
              x-kubernetes-preserve-unknown-fields: true    
              required:
                - datbaseName
                - engineVersion
                - parameterGroupFamily
                - deletionProtection
                - dbClusterInstanceClass
                - dbInstanceCount
            status:
              type: object
              description: Status defines the observed state
              properties:
                outputs:
                  description: Freeform field containing status information for regional mysql
                  type: object
                  x-kubernetes-preserve-unknown-fields: true    