---
apiVersion: aws.v1beta1.afterpay.cloud/v1beta1
kind: RMysql
metadata:
  name: regional-mysql-deleteme-v1
  namespace: pe
  labels:
    version: v1beta1
    rerun: "true"
spec:
  datbaseName: mysql
  engineVersion: 8.0.mysql_aurora.3.03.1
  parameterGroupFamily: aurora-mysql8.0
  deletionProtection: false
  dbClusterInstanceClass: db.r5.large
  dbInstanceCount: 1
  compositionSelector:
    matchLabels:
      version: v1beta1
      provider: aws
      cluster: regional
      engine: mysql
      spike: "true"