---
apiVersion: aws.v1beta1.afterpay.cloud/v1beta1
kind: RMysql
metadata:
  name: regional-mysql-deleteme-v1
  labels:
    version: v1beta1
spec:
  datbaseName: mysql
  engineVersion: "8.0"
  parameterGroupFamily: aurora-mysql8.0
  deletionProtection: false
  dbClusterInstanceClass: db.r5.large
  dbInstanceCount: 2 #### How ?

### Full Example
---
apiVersion: aws.v1beta1.afterpay.cloud/v1beta1
kind: RMysql
metadata:
  name: regional-mysql-deleteme-v1
  labels:
    version: v1beta1
spec:
  datbaseName: mysql
  engineVersion: "8.0"
  parameterGroupFamily: aurora-mysql8.0
  deletionProtection: false
  dbClusterInstanceClass: db.r5.large
  dbInstanceCount: 2
  skipFinalSnapshot: true
  performanceInsightsEnabled: true
  backupRetentionPeriod: 7
  preferredBackupWindow: 12:00-13:00
  preferredMaintenanceWindow: wed:10:00-wed:11:00
  applyImmediately: true
