---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xrmysql.aws.v1beta1.afterpay.cloud
  labels:
    version: v1beta1
    provider: aws
    cluster: regional
    engine: mysql
    spike: "true"
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: aws.v1beta1.afterpay.cloud/v1beta1
    kind: XRMysql
  patchSets:
    - name: metadata
      patches:
        - fromFieldPath: metadata.labels
          toFieldPath: metadata.labels
  resources:
    << $replica := .config.rds.replicas | coll.Pick .config.rds.primary ->>
    - name: mysql-security-group
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroup
        spec:
          forProvider:
            name: mysql-aurora-securitygroup
            region: << .config.aws.region >>
            <<- range $value := $replica >>
            vpcId: << $value.vpcId >>
            <<- end >>
        patches:
          - type: PatchSet
            patchSetName: metadata
          - type: ToCompositeFieldPath
            fromFieldPath: status.atProvider.id
            toFieldPath: status.share.securityGroupId
            policy:
              fromFieldPath: Optional
    
    - name: mysql-ingress-security-group-rule
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroupRule
        metadata:
          name: mysql-ingress-rules
        spec:
          forProvider:
            type: ingress
            region: << .config.aws.region >>
            cidrBlocks:
            <<- range $value := $replica >>
              <<- range $cidr := $value.dbIngressCIDRs >>
              - << $cidr >>
              <<- end >>
            <<- end >>
            fromPort: << .config.rds.mysql.port >>
            toPort: << .config.rds.mysql.port >>
            protocol: tcp
        patches:
          - type: PatchSet
            patchSetName: metadata
          - fromFieldPath: status.share.securityGroupId
            toFieldPath: spec.securityGroupId
            policy:
              fromFieldPath: Required      

    - name: mysql-egress-security-group-rule
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroupRule
        spec:
          forProvider:
            type: egress
            region: << .config.aws.region >>
            cidrBlocks:
              - 0.0.0.0/0
            fromPort: 443
            toPort: 443
            protocol: tcp
        patches:
          - type: PatchSet
            patchSetName: metadata
          - fromFieldPath: status.share.securityGroupId
            toFieldPath: spec.securityGroupId
            policy:
              fromFieldPath: Required

    - name: mysql-cluster-parameter-group
      base:
        apiVersion: rds.aws.upbound.io/v1beta1
        kind: ClusterParameterGroup
        spec:
          forProvider:
            region: << .config.aws.region >>
            family: << .config.rds.mysql.family >>
            parameter:
              - name: character_set_server
                value: utf8
              - name: character_set_client
                value: utf8
              - name: time_zone
                value: UTC
              - name: character_set_connection
                value: utf8
              - name: character_set_database
                value: utf8
              - name: character_set_results
                value: utf8
              - name: binlog_format
                value: ROW
                applyMethod: pending-reboot
              - name: server_audit_logging
                value: '1'
              - name: server_audit_logs_upload
                value: '1'
              - name: server_audit_events
                value: CONNECT,QUERY_DCL,QUERY_DDL
          providerConfigRef:
            name: default
        patches:
          - type: PatchSet
            patchSetName: metadata
          - fromFieldPath: spec.parameterGroupFamily
            toFieldPath: spec.forProvider.family
            policy:
              fromFieldPath: Required
          - type: ToCompositeFieldPath
            fromFieldPath: status.atProvider.id
            toFieldPath: status.share.clusterParameterGroupId
            policy:
              fromFieldPath: Optional

    - name: mysql-parameter-group
      base:
        apiVersion: rds.aws.upbound.io/v1beta1
        kind: ParameterGroup
        spec:
          forProvider:
            region: << .config.aws.region >>
            family: << .config.rds.mysql.family >>
            parameter:
              - name: "max_connections"
                value: "1000"
          providerConfigRef:
            name: default
        patches:
          - type: PatchSet
            patchSetName: metadata
          - fromFieldPath: spec.parameterGroupFamily
            toFieldPath: spec.forProvider.family
            policy:
              fromFieldPath: Required
          - type: ToCompositeFieldPath
            fromFieldPath: status.atProvider.id
            toFieldPath: status.share.parameterGroupId
            policy:
              fromFieldPath: Optional
