---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xrmysql.aws.v1beta1.afterpay.cloud
  labels:
    version: v1beta1
    provider: aws
    cluster: regional
spec:
  group: aws.v1beta1.afterpay.cloud
  names:
    kind: XRMysql
    plural: xrmysql
  claimNames:
    kind: RMysql
    plural: rmysql
  versions:
    - name: v1beta1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                datbaseName:
                  type: string
                engineVersion:
                  type: string
                parameterGroupFamily:
                  type: string
                replicas:
                  type: array
                  items:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true  
              required:
                - datbaseName
                - engineVersion
                - parameterGroupFamily
                - replicas
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                share:
                  description: Share status between resources
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                outputs:
                  description: Freeform field containing status information for regional postgres
                  type: object
                  x-kubernetes-preserve-unknown-fields: true       